export const mockTickets = [
  {
    id: 1,
    title: 'Concert A',
    imageName: 'logo1.png',
    date: '2023-08-15',
    venue: 'Stadium A',
    venueLocation: '123 Street A',
    price: 100,
    transportation: { origin: 'City A', price: 20 },
    food: { data: { food: 'Burger', drink: 'Coke', price: 15 } },
    qrCode: 'https://mediafiches.ac-creteil.fr/IMG/png/exemple_qrcode.png',
  },
  {
    id: 2,
    title: 'Concert B',
    imageName: 'logo2.jpg',
    date: '2023-09-10',
    venue: 'Stadium B',
    venueLocation: '456 Street B',
    price: 150,
    transportation: { origin: 'City B', price: 25 },
    food: { data: { food: 'Pizza', drink: 'Pepsi', price: 20 } },
    qrCode: 'https://mediafiches.ac-creteil.fr/IMG/png/exemple_qrcode.png',
  },
  {
    id: 3,
    title: 'Concert C',
    imageName: 'logo3.webp',
    date: '2023-10-05',
    venue: 'Stadium C',
    venueLocation: '789 Street C',
    price: 200,
    transportation: { origin: 'City C', price: 30 },
    food: { data: { food: 'Sushi', drink: 'Tea', price: 25 } },
    qrCode: 'https://mediafiches.ac-creteil.fr/IMG/png/exemple_qrcode.png',
  },
];
